version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: [ "--host", "0.0.0.0", "--port", "8000", "--reload" ]
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 27017
    volumes:
      - ${PWD}/testerozza:/opt/code-scribes/testerozza

  db:
    image: mongo
    restart: always
    ports: 
      - 27017:27017
    environment:
      MONGO_INIT_DB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INIT_DB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONOG_INITDB_DATABASE: testerozza
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js
      - dbdata:/data/db

volumes:
  dbdata:
